import './globals.css';

import localFont from 'next/font/local';
import { Toaster } from 'sonner';

import AutoRefreshToken from '@components/auth-refresh-token';
import AppProvider from 'src/providers/app-provider';

const myLocalFont = localFont({
  src: [
    {
      path: '../../public/font/AvenirNextLTPro-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/font/AvenirNextLTPro-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/font/AvenirNextLTPro-Demi.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/font/AvenirNextLTPro-Heavy.otf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/font/AvenirNextLTPro-Bold.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={myLocalFont.className}>
        <Toaster />
        <AppProvider>
          {children}
          <AutoRefreshToken />
        </AppProvider>
      </body>
    </html>
  );
}
